### ISSUE TITLE
Performance: Establish/Cleanup are being called for every "It" (in Visual Studio IDE)

### ISSUE THREAD

**Issue by riotgibbon** [machine/machine.vstestadapter#8]
Hi there,

It looks like if you use the MSpec Test Adaptor from the Test Explorer in VS2013, then the context and because statements get re-run for each It declaration. I only realised when I added some web-service integration tests, and my daily limit popped!

great tool, use it all time

Toby

**Comment by ivanz** [comment]
Had a look into this and the issue is that VS passes a list of tests to run (e.g. `It`), so when the adapter runs each `It` it's wrapped in a new test context - hence Establish+Because+Cleanup get called for each `It` (for reference the code is here: https://github.com/machine-visualstudio/machine.vstestadapter/blob/master/Source/Machine.Specifications.VSRunner/AppDomainExecutor.cs#L31 )

Now the issue is that MSpec has public API to either run a single 'It', a whole class or a whole assembly, but not a subset of `It` in either a class or assembly (which is what effectively happens when you make a selection in VS). 

It won't be hard to add that extra filtering functionality to MSpec, so that the test adapter can use it. I will raise an issue, proposal and potentially pull request with MSpec and update this ticket with link to the MSpec issue when I get a chance to do that stuff.

**Comment by ivanz** [comment]
Another solution would be to do something like this: https://github.com/machine/machine.specifications.runner.dnx/blob/master/src/machine.specifications.runner.dnx/Program.cs#L32

However even them I am not sure if `runner.RunMember(assembly, specification.FieldInfo)` won't run Establish/Because again.

**Comment by ivanz** [comment]
FYI I have opened a pull request in MSpec to see if we can resolve this in mspec directly: https://github.com/machine/machine.specifications/issues/287

**Comment by ivanz** [comment]
FYI in the just released 2.0.0-beta1 there is a major performance improvement when using the adapter in CI (and running whole assemblies). Potentially also when doing "Run All" in the IDE (depending on whether it says "run this list of tests" or "run this list of assemblies"), but I haven't tested that yet.

**Comment by ivanz** [comment]
Moved to https://github.com/machine/machine.specifications/issues/325
