### ISSUE TITLE
CodeLens support

### ISSUE THREAD

**Issue by patroza** [machine/machine.vstestadapter#9]
Hi,

Is there a possiblity for CodeLens support? Any blockers known?

Thanks

**Comment by dionbr** [comment]
Given CodeLens is in VS2015 Pro now any chance of this being looked at?

**Comment by JonathanWilkins** [comment]
Yeah will start to have a look at this soon

**Comment by ivanz** [comment]
I believe that Visual Studio doesn't handle this for MSpec, because the mspec tests are fields rather than methods. I think that's also the reason why it doesn't display the test result indicator for mspec tests on top of the field (the green tick, etc.)

Also note that I believe for the codelens support to work in general you need the tests to be in a "Unit Test" Project and not just a class library project.

**Comment by sickboy** [comment]
Also in the test suites I found so far, helper methods (methods not part of the entry method of the test), are not included in marking called code as tested by this test. (hope this makes some sense)

**Comment by ivanz** [comment]
Moved to https://github.com/machine/machine.specifications/issues/326
